services:
  trip_web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: trip_web
    image: trip_web:0.1
    command: bash -c "bundle exec rake db:create && bundle exec rake db:migrate && ./bin/rails server -b 0.0.0.0 -p 3000"
    ports:
      - "5555:3000"
    networks:
      - trip_network
    volumes:
      - ./:/rails

networks:
  trip_network:
    external: true