services:
  trip_db:
    image: postgres:latest
    container_name: trip_db
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
    ports:
      - "5433:5432"
    networks:
      - trip_network

  trip_pgadmin:
    image: dpage/pgadmin4
    container_name: trip_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "8888:80"
    depends_on:
      - trip_db
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - trip_network

volumes:
  pgadmin_data:

networks:
  trip_network:
    external: true
